name: XH
description: $description
version: '${version}'

main: io.github.liyughj.xH.XH
api-version: '26.2'
load: POSTWORLD
depend: [ProtocolLib]

authors: [ 恪深 ]

commands:
  xh:
    description: XH插件主命令
    usage: /xh [give|reload|lore|help]
    aliases: [xH]
    permission: xh.use
    permission-message: '§c你没有权限使用此命令'

permissions:
  xh.use:
    description: 允许使用 /xh 命令
    default: true
  xh.admin:
    description: 允许重载插件配置与 /xh give
    default: op
